baseurl = "https://aboreal.rbind.io/"
title = "aurore"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Aurore Paligot"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Aurore Paligot"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    #headline = "Ghostwriter example"
    description = "a data journey"
    github = "https://github.com/aurorepaligot"
    #gitlab = "https://gitlab.com/XXX"
    linkedin = "https://linkedin.com/in/aurorepaligot/"
    #gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/AurorePaligot"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    #facebook = "https://www.facebook.com/username"
    email = "aurorepaligot@hotmail.com"
    opengraph = false
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = false
    readingTimeText = "Estimated reading time:"
    fathomUrl = ""
    fathomSiteId = ""

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
